# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a332945251dbcf2a4cb9d4d19bc14ac83c4f4ab139bca45c9b953e309d1073ed304073c157efb238a92cc52c52005e87d6369104f5b557bddcc233406e8ac63b

test:
  secret_key_base: 5488e7119ccb0308ee04a2e7d7f62cb925bc2aa4ec95d5418e7a8dbc9f0d93c22a54bed90006db2eab5e8d6f3d97d6b02fdde6a5076c9aaf0373ca3f84085552

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
